





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyFileVersion("2.0.3.1")]
 [assembly: AssemblyVersion("2.0.3.1")]
